export { TestappComponent } from "./testapp/testapp.component";
export { HeaderComponent } from "./header/header.component";
export { FooterComponent } from "./footer/footer.component";
export { RegisterComponent } from "./register/register.component";
export { RegisterformComponent } from "./registerform/registerform.component";
export { LoginComponent } from "./login/login.component";
export { LateralmenuComponent } from "./lateralmenu/lateralmenu.component";
export { AccountComponent } from "./account/account.component";
export { DentistsComponent } from "./dentists/dentists.component";
export { PatientsComponent } from "./patients/patients.component";
export { ProfileComponent } from "./profile/profile.component";
export { DashboardComponent } from "./dashboard/dashboard.component";
export { SuccessregisterComponent } from "./successregister/successregister.component";
export { SuccesspatientregisterComponent } from "./successpatientregister/successpatientregister.component";
export { RegisterdoctorComponent } from "./registerdoctor/registerdoctor.component";
export { MessageComponent } from "./message/message.component";
export { NewappointmentComponent } from "./newappointment/newappointment.component";
export { AppointmentsComponent } from "./appointments/appointments.component";

// export { FruitbannerboxComponent } from "./fruitbannerbox/fruitbannerbox.component";
